[IV-21-22] Objetivo 1
morevi/jobcontrol pull request #13
Opened 2021-11-16 15:34 UTC by morevi

- Se han añadido varias HU en forma de issues.
- Se han añadido varios milestones
- Se añade documentación generada durante la planificacion. Closes #11

2021-11-16 15:42 UTC, morevi commented
@eantoniocalo18

2021-11-16 17:25 UTC, morevi commented
@JJ Listo para revisión

2021-11-19 06:35 UTC, JJ requested changes
Revisa tus issues y el resto contra la lista de comprobación del objetivo 1. Las HUs deben proporcionar un beneficio al usuario y tener relación con la lógica de negocio. Si son cosas que hay que hacer pero no dan ningún beneficio, son issues.

2021-11-19 06:35 UTC, JJ commented on docs/planificacion.md
> +Implementación de esta propia página en issues y milestones.
¿Has revisado la lista de comprobación de este objetivo? ¿Entiendes que siempre tienen que ser productos mínimamente viables y relacionados con el código? ¿De qué forma algo relacionado con la asignatura tendrá relación con el código o es un producto?

2021-11-19 18:12 UTC, morevi commented
@JJ Listo para revision

2021-11-21 08:49 UTC, JJ requested changes
Revisa el concepto de historia de usuario. También las HUs parece que se asignan de forma arbitraria a hitos. 
El hito 1 es vago (clases que hagan qué o que sean viables de qué forma); hay un gran hueco entre el 1 y el 2, y este también es vago (un API no es un producto). El resto debes seguir las mismas reglas.

2021-11-22 20:38 UTC, morevi commented
Se han repasado los conceptos, y como consecuencia he vuelto a reescribir las HUs y los Milestonse.
@JJ 
Listo para revisión

2021-11-23 11:07 UTC, JJ requested changes
Te agradecería que consultaras [la lista de comprobación](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura#listas-de-comprobaci%C3%B3n) de este objetivo antes de volver a enviarlo. En general, tienes que entender todavía (y plasmarlo aquí) el concepto de "usuario", "lógica de negocio" y por supuesto historia de usuario. Te he indicado en 2 el problema, pero tendrás que revisar todas de acuerdo con la lista anterior.

2021-11-23 11:07 UTC, JJ commented on docs/planificacion.md
> +- El empleado debe indicar el horario que ha seguido de forma mensual, para que los superiores confirmen el pago.
Un user journey debe incluir context. ¿Cuando lo hace? ¿Por qué dice el horario? ¿No tiene otra forma de hacerlo? ¿El empleado obtiene algún beneficio con eso? ¿Dónde se indicaría el horario?

2021-11-23 11:07 UTC, JJ commented on docs/planificacion.md
> +- E1 Como empleado quiero manejar horarios, para que los cargos superiores sepan cuanto deben pagarme.
¿Por qué querría un empleado hacer tal cosa? ¿No será que el gerente quiere que lo hagan para algo? ¿En serio que los horarios los pone el usuario?

2021-11-24 10:20 UTC, morevi commented on docs/planificacion.md
> +- El empleado debe indicar el horario que ha seguido de forma mensual, para que los superiores confirmen el pago.
- ¿Cuándo? El empleado podrá, indicar el horario cuando le apetezca y le sea más sencillo. Por lo general se entrega una vez al mes.
- El registro horario se hace, porque es obligatorio (no tiene nada que ver con el pago, me he informado y tengo que cambiarlo).
- La forma actual de hacerlo es coger el excel template, modificarlo para que se adapte al mes que estas entregando, y luego rellenar usando el horario que hayas llevado
de ese mes. La idea es que el empleado pueda indicarlo, de forma rápida, sin estar pendiente de nada (días del mes, mes, festivos, etc).
- El beneficio del empleado, será la comprobación de los datos y la confección automática de este documento.
- ¿Donde? ¿Al microservicio? Esta no la entiendo bien.

Además se planea que el input del empleado sea de forma horario+horasPorProyecto, para que el empleado tenga que rellenar el minimo de información. El programa tratará de generar por un lado el registro horario, y por otro mejorar la gestión/planificación de la empresa.

2021-11-24 10:21 UTC, morevi commented on docs/planificacion.md
> +- E1 Como empleado quiero manejar horarios, para que los cargos superiores sepan cuanto deben pagarme.
- El registro horario es obligatorio hacerlo.
- Lo del "pago" es un error.

2021-11-25 13:24 UTC, morevi commented
@JJ Listo para revisión

2021-11-26 08:46 UTC, JJ approved these changes
Por favor, trata de seguir la regla de que lo que hay que describir es un producto, y de qué forma es viable, no "cosas que tiene este producto". Aunque lo primero incluye lo segundo, de lo segundo no sale necesariamente lo primero. En cuanto a los issues, lo suyo hubiera sido que @eantoniocalo18 los hubiera creado, y que los priorizara, ahora tendrás que dejar claro cuando se ponga a trabajar en este objetivo por dónde tiene que empezar y qué PMV tendría que tratar de hacer entero o en parte.

2021-11-26 08:47 UTC, JJ approved these changes
Con el fondo este negro no veo lo que está marcado, de verdad... :+1:

2021-11-28 12:47 UTC, merged