IV Objetivo 2 [IV-21-22]
morevi/jobcontrol pull request #33
Opened 2021-11-29 20:41 UTC by eantoniocalo18

Entrega del objetivo 2 incluyendo:
- Elección del lenguaje de programación 
- Actualización de .gitignore para python
- Se incluyen #29 y #30 
- Se ha implementado las clases Horario y Proyecto y los problemas relacionados durante el proceso se han reflejado en #31 y #32

2021-11-29 20:42 UTC, eantoniocalo18 commented
Cuando puedas @morevi, enlaza este PR al Milestone 0 y los issues correspondientes

2021-11-29 21:29 UTC, morevi commented on src/proyecto.py
> +        "Método que devolverá true si el proyecto ha sido terminado"
El comentario es erróneo

2021-11-29 21:30 UTC, morevi commented on src/usuario.py
> +class usuario:
Nombres de clases deben comenzar por Mayuscula

2021-11-29 21:32 UTC, morevi commented on src/usuario.py
> +    Clase utilizada para representar un Proyecto.
Clase usuario/empleado, no proyecto

2021-11-29 21:38 UTC, morevi approved these changes
Me gusta la idea de representar tambien poder representar los días.
A partir de aquí se podrá avanzar a buen ritmo.

Hay algunos errores, pero nada grave que no se pueda arreglar en un commit de typos.
👍🏼

2021-11-30 10:14 UTC, morevi approved these changes
Perfecto! 👍🏼

2021-12-02 09:53 UTC, eantoniocalo18 commented
@JJ Listo para revisión

2021-12-03 07:52 UTC, JJ requested changes
Repetidamente se ha dicho que un issue no es "crear no sé qué" y se soluciona con "esto está creado". Por favor, revisa la lista de comprobación y, si es necesario, pégala en el cuerpo del PR.

2021-12-03 07:52 UTC, JJ commented on src/dia.py
> +# Este archivo dia.py contiene la implementaciÃ³n de la clase dia.
???

2021-12-03 07:52 UTC, JJ commented on src/dia.py
> +    def calcular_horas():
¿Esto no sería hora_fin - hora_inicio - horas_descanso? ¿Por qué no es un atributo de clase?

2021-12-03 07:52 UTC, JJ commented on src/horario.py
> +        self.nombre = usuario_relacionado
Si el usuario tiene un id, ¿por qué se usa el nombre?

2021-12-03 07:52 UTC, JJ commented on src/usuario.py
> +    email : str
¿En qué ayuda esto a la lógica de negocio?

2021-12-03 10:23 UTC, eantoniocalo18 commented on src/dia.py
> +    def calcular_horas():
Había pensado declararlo como atributo de la clase pero he pensado que es más útil que puedas ir añadiéndole los datos progresivamente, es decir, si tú quieres añadir solo la hora de entrada y cuando salgas la hora de salida y llamar al método calcular_horas  una vez se haya terminado todo el horario completo.

2021-12-03 10:26 UTC, eantoniocalo18 commented on src/horario.py
> +        self.nombre = usuario_relacionado
Porque el id es un identificador único y los demás datos del usuario sirven para ser reflejados a la hora de subir sus horarios en un proyecto (pj Participantes del proyecto: Nombre-Apellidos)

2021-12-03 10:43 UTC, eantoniocalo18 commented on src/usuario.py
> +    email : str
Tiene razón, se ha creado #34 representando el problema

2021-12-03 10:50 UTC, eantoniocalo18 commented on src/horario.py
> +        self.nombre = usuario_relacionado
Tiene razón, es necesario que el atributo que represente la asociación entre las clases Usuario y Horario sea único, se ha representado el problema en #35

2021-12-03 12:38 UTC, eantoniocalo18 commented
@JJ Listo para revisión

2021-12-05 20:26 UTC, JJ requested changes
Aparte de los errores señalados y que realmente no se han solucionado, has modificado en un solo commit cosas de dos issues que has abierto ex profeso más otros dos de antes, y que siguen sin representar ningún problema. 
La mayoría del código sigue teniendo como último commit "creación clase xxx" en vez de indicar como resuelve un problema formulado en un issue. Por ejemplo, "clase Dia" no está claro que resuelva ningún problema ni sirva para nada en la lógica de negocio.

2021-12-05 20:26 UTC, JJ commented on src/dia.py
> +# Este archivo dia.py contiene la implementaciÃ³n de la clase dia.
Sigue estando el error.

2021-12-05 20:26 UTC, JJ commented on src/dia.py
> +        uuid o id que identifica cada día único
¿En serio necesitáis un ID para representar un día? ¿No será suficiene con la fecha?

2021-12-05 20:26 UTC, JJ commented on src/dia.py
> +    def calcular_horas():
Pienses lo que pienses, tienes que ponerlo en un issue y expresar el problema que hay. Todo lo que  comentas, ¿en qué HU/issue lo dice?

2021-12-05 20:26 UTC, JJ commented on src/horario.py
> +        self.horas_semanales = horas_semanales
¿Un horario tiene horas semanales y días trabajados? ¿Un usuario puede tener varios horarios? Si no, ¿por qué necesitas un id?

2021-12-05 20:26 UTC, JJ commented on src/usuario.py
> +    email : str
El "problema" no es lo que yo te diga aquí, sino que tienes que crear un issue con los diferentes problemas planteados. Y el email ha desaparecido, pero el comentario sigue.

2021-12-06 14:49 UTC, eantoniocalo18 commented
@JJ Listo para revisión

2021-12-07 09:17 UTC, eantoniocalo18 commented
> Aparte de los errores señalados y que realmente no se han solucionado, has modificado en un solo commit cosas de dos issues que has abierto ex profeso más otros dos de antes, y que siguen sin representar ningún problema. La mayoría del código sigue teniendo como último commit "creación clase xxx" en vez de indicar como resuelve un problema formulado en un issue. Por ejemplo, "clase Dia" no está claro que resuelva ningún problema ni sirva para nada en la lógica de negocio.

No sé cómo solucionar la parte de que "la mayoría del código sigue teniendo como último commit "creacion de xxx" ". He modificado el issue #32  en el que se intenta representar de una manera más clara el problema que ha surgido y cuya solución viene dada con la creación de la clase Dia en el commit b1324f10ba0b99aaf4e337d395f8b02483526052

2021-12-07 11:55 UTC, JJ commented
> > Aparte de los errores señalados y que realmente no se han solucionado, has modificado en un solo commit cosas de dos issues que has abierto ex profeso más otros dos de antes, y que siguen sin representar ningún problema. La mayoría del código sigue teniendo como último commit "creación clase xxx" en vez de indicar como resuelve un problema formulado en un issue. Por ejemplo, "clase Dia" no está claro que resuelva ningún problema ni sirva para nada en la lógica de negocio.
> 
> No sé cómo solucionar la parte de que "la mayoría del código sigue teniendo como último commit "creacion de xxx" ". He modificado el issue #32 en el que se intenta representar de una manera más clara el problema que ha surgido y cuya solución viene dada con la creación de la clase Dia en el commit [b1324f1](https://github.com/morevi/jobcontrol/commit/b1324f10ba0b99aaf4e337d395f8b02483526052)

Si no has escrito el código solucionando ningún problema, lo mejor que haces es borrarlo y empezar de nuevo. No se trata de que enlacéis cosas, se trata de que sigáis buenas prácticas para que el código resuelva el problema que tiene que resolver.

2021-12-07 12:00 UTC, JJ requested changes
Sigues sin responder a los múltiples comentarios, y sigues desarrollando la mayor parte del código sin indicar qué problema se resuelve ni por qué usas esas funciones y atributos.

2021-12-07 12:00 UTC, JJ commented on src/dia.py
> +    def calcular_horas():
Sigues sin responder esto.

2021-12-07 12:00 UTC, JJ commented on src/horario.py
> +        self.horas_semanales = horas_semanales
Y esto

2021-12-07 12:00 UTC, JJ commented on src/proyecto.py
> +    def is_finalizado():
¿Donde dice que hay que hacer esto y no, por ejemplo, borrar el proyecto?

2021-12-07 12:00 UTC, JJ commented on src/proyecto.py
> +    def horas_restantes():
¿Cómo se supone que va a calcular esto? ¿En base a qué? ¿La planificación, dónde aparece? ¿Ves lo que pasa si no planteas ningún problema y pones cosas sin responder a ningún criterio? @morevi, ¿no tienes nada que decir sobre esto?

2021-12-07 12:00 UTC, JJ commented on src/usuario.py
> +    def confirmar_horario():
Esto está creado en un commit que dice "creación clase usuario". Ni se sabe qué hace, ni qué debe hacer, ni cómo va a confirmar el horario (o no) en base al nombre y apellidos del usuario. Además, cada clase debe hacer una cosa y sólo una cosa. Si representa a un usuario, representa a un usuario.

2021-12-08 11:41 UTC, eantoniocalo18 commented
Se va a cerrar este PR, para crear uno desde 0, con una mayor limpieza y con los contenidos mejor enfocados

2021-12-08 11:41 UTC, closed without merging