Update IV Objetivo 2 [IV-21-22]
morevi/jobcontrol pull request #43
Opened 2021-12-08 18:14 UTC by eantoniocalo18

Entrega del objetivo 2 incluyendo:
- Elección del lenguaje de programación 
- Actualización de .gitignore para python
- Se incluyen #29 y #30 
- Se ha implementado las clases Horario y Proyecto y los problemas relacionados durante el proceso se han reflejado en #41 y #42

2021-12-08 18:49 UTC, morevi approved these changes

2021-12-08 19:44 UTC, morevi requested changes
- [x] Los nombres de los .py deben estar en minúscula.
- [x] vi.yaml -> iv.yaml
@eantoniocalo18

2021-12-09 07:35 UTC, morevi approved these changes

2021-12-09 07:36 UTC, eantoniocalo18 commented
@JJ Listo para revisión

2021-12-10 11:08 UTC, JJ requested changes
Me da la impresión de que más allá de poner nombres razonables, no se está tratando de implementar en estructuras de datos diferentes un modelo del problema analizado en profundidad.

2021-12-10 11:08 UTC, JJ commented on src/horario.py
> +        uuid o id que identifica cada horario único
¿Por qué se tiene que identificar un horario de forma única? ¿En qué sirve eso a la lógica de negocio?

2021-12-10 11:08 UTC, JJ commented on src/horario.py
> +	" Método que devolverá la diferencia entre horas_semanales y horas_trabajadas"
¿De dónde sale horas semanales?

2021-12-10 15:26 UTC, eantoniocalo18 commented on src/horario.py
> +        uuid o id que identifica cada horario único
Se ha presentado el problema en #48

2021-12-10 18:38 UTC, eantoniocalo18 commented
Se ha actualizado la descripción de los issues y corregido los errores.
@JJ Listo para revisión.

2021-12-11 08:50 UTC, JJ requested changes
Este objetivo es fundamental, y recibe una buena cantidad de puntos en la nota final. Contiene una serie de conceptos fundamentales sobre diseño y programación. Un poco de esfuerzo por entender esos conceptos, que implican principalmente pasar de una serie de necesidades a estructuras de datos que cubran esas necesidades, es fundamental. Y eso por parte de todas las partes implicadas.

2021-12-11 08:50 UTC, JJ commented on src/horario.py
> +	self.horas_trabajadas = horas_trabajadas
Por favor, intentad compilar lo que estáis haciendo.

2021-12-11 08:50 UTC, JJ commented on src/proyecto.py
> +    def __init__(self, id, planificacion, horarios):
A ver, no es que yo entienda mucho de esto. Pero ¿en un proyecto participa todo el mundo? ¿O sólo puedes poner horas en los proyectos que participas? ¿Hacemos por favor un intento de modelar de verdad el dominio del problema siguiendo domain driven design?

2021-12-11 18:07 UTC, eantoniocalo18 commented
Se han corregido los errores, ampliado el análisis de los issues #41 y #42 y también se ha profundizado en el funcionamiento que tendrá la clase proyecto.
@JJ Listo para revisión.

2021-12-12 09:45 UTC, JJ approved these changes
Podrías añadir un poco de validación a lo que pasas al constructor, para asegurarte que es lo qeu dice, pero si @morevi no te lo pide, no voy a ser yo quien lo haga...

2021-12-12 14:47 UTC, morevi approved these changes

2021-12-12 14:58 UTC, merged