[IV-21-22] Objetivo 3
morevi/jobcontrol pull request #47
Opened 2021-12-08 20:12 UTC by morevi

- Closes #44 
- Closes #45 
- Closes #46 

### Checklist
- [ ] ¿Incluye el fichero las claves de todos los objetivos anteriores?
- [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un issue?
- [ ] ¿Ese issue está asignado a un milestone?
- [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de dependencias el que se use como gestor de tareas?
- [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?

2021-12-08 20:20 UTC, morevi commented
Listo para revisión! @JJ

2021-12-09 19:20 UTC, JJ requested changes
Por favor, revisa bien el guión de este objetivo y los errores frecuentes. También los errores ortográficos.

2021-12-09 19:20 UTC, JJ commented on docs/deps_and_runner.md
> +- frecuente actividad de mantenimiento del proyecto
Se te ha olvidado el principal: que entienda pyproject.tom. pip no lo hace.
Por otro lado, no sé quién ha pedido que elijáis un gestor de dependencias. Lo que hay que elegir es un task runner.

2021-12-09 19:20 UTC, JJ commented on docs/deps_and_runner.md
> +- facil de usar
¿Cómo decides que es fácil de usar? Also: typo

2021-12-10 10:41 UTC, morevi commented
@JJ Listo para revisión.

Hay algunas cosas que no puedo hacer hasta que el PR del compañero reciba el pasa:
- la descripción de las clases en el readme
- las claves en el fichero iv.yaml

2021-12-10 11:09 UTC, JJ reviewed
:+1:

2021-12-11 13:04 UTC, merged