[IV-21-22] Objetivo 4
morevi/jobcontrol pull request #54
Opened 2021-12-14 20:33 UTC by morevi

A partir de 
- #26 

Se han creado:
- #50
-  #51 

Y para tomar decisiones sobre la elección del framework de tests y la librería de aserciones
- #52 
- #53 

### Checklist
* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de usuario que desarrolla, pasando por el mensaje de commit y el issue correspondiente?
* [ ]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases, módulos o paquetes más fundamentales frente a otros, movidos a otro PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y del de *test runner*?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se considere viable?

2021-12-14 21:21 UTC, morevi commented
⛹ Revisores → @modejota @Pablont98 @Balrrach

2021-12-15 16:43 UTC, Pablont98 commented
Tras revisar el proyecto, he de decir que esta bastante completo y bien.
Como un apunte: Sería conveniente que pusieras comentarios en los .py de los test para saber que se esta haciendo con mas claridad.

2021-12-15 17:00 UTC, Balrrach commented
Podria ser mejor cambiar la estructura de los commits para que al inicio solo aparezcan los issues a los que esta relaccionado ya que esta primera linea a modo de titular tiene un tamaño muy limitado.

2021-12-15 17:01 UTC, Balrrach commented
Lo adecuado es documentar los cambios en el codigo como has hecho en 9d8bc2

2021-12-15 17:21 UTC, Balrrach requested changes

2021-12-15 17:21 UTC, Balrrach commented on docs/tests.md
> +# Marco de tests
Justificacion adecuada y extensa. Enhorabuena.

2021-12-15 17:21 UTC, Balrrach commented on pyproject.toml
> +path = ["unit_tests", "tests"]
Donde esta unit_tests?

2021-12-15 17:22 UTC, Balrrach commented
Los tests me parecen correctos porque verdaderamente testean la logica de negocio descrita en  #51.

2021-12-15 18:15 UTC, modejota commented
> Tras revisar el proyecto, he de decir que esta bastante completo y bien. Como un apunte: Sería conveniente que pusieras comentarios en los .py de los test para saber que se esta haciendo con mas claridad.

+ 1 a esto. Si no quieres poner comentarios para no emborronar código, utilizaría nombre de variables que sean más descriptivos que "horario" o "error".

2021-12-15 18:41 UTC, morevi commented on pyproject.toml
> +path = ["unit_tests", "tests"]
Antes también tenía integration tests, pero decidí dejarlo por ahora todo en la carpeta tests. Lo quito.

2021-12-15 19:17 UTC, morevi commented
Trataré de usar a partir de ahora en los mensajed de commit, un mix de lo que tenía antes con lo que @Balrrach ha comentado.
No utilizaré las directivas ("Close", etc) en la primera línea del commit, porque como has dicho, ocupa espacio, pero también queremos que la primera línea describa bien qué hace el commit. Relacionar el commit de forma corta haciendo #XX y luego en el cuerpo usar la palabra clave me ha parecido mejor opción. Me refiero a e5b3d55

2021-12-15 19:21 UTC, morevi commented
@JJ Listo para revisión.

2021-12-16 19:23 UTC, JJ approved these changes
:+1: la verdad es que no tengo mucho que añadir. Lo señalado no impide que se cumpla el objetivo.

2021-12-16 19:23 UTC, JJ commented on docs/tests.md
> +Se ha elegido WARD.
:clap:

2021-12-16 19:23 UTC, JJ commented on tests/test_horario.py
> +        'L': [(time(9, 0), 8)],
No uses literales en el código, usa constantes. También estás repitiendo la misma constante, defínela como constante... Y usa un bucle para definirla.

2021-12-16 20:36 UTC, merged