[IV-21-22] Objetivo 5
morevi/jobcontrol pull request #58
Opened 2021-12-17 08:52 UTC by morevi

- Closes #56 
- Closes #57 
- Documentación sobre la elección realizada en [docker.md](https://github.com/morevi/jobcontrol/blob/objetivo-5/docs/docker.md)

## Checklist
* [ ]  ¿Se han seguido las buenas prácticas en las órdenes que construyen la imagen?
* [ ]  ¿La imagen incluye sólo y exclusivamente la infraestructura necesaria para pasar los tests?
* [ ]  ¿Se han documentado y enlazado los commits a las imágenes que se han testeado?
* [ ]  ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los tests que se van a lanzar?
* [ ]  ¿Se han establecido claramente los criterios de búsqueda y de aceptación de la imagen base?

2021-12-17 08:55 UTC, morevi commented
⛹ Revisores → @Antobio17 @gomares @amerigal

2021-12-17 09:36 UTC, Antobio17 reviewed
Aquí te dejo mi revisón :+1:

2021-12-17 09:36 UTC, Antobio17 commented on .github/workflows/dockerhub.yml
> +      - objetivo-5
El problema de esto es que, en otro objetivo (u otra rama diferente) haces un push modificando algo relacionado con el contenedor no va a subirse a Dockerhub. Por ejemplo si esos cambios están relacionado con los tests para poder ser ejecutados al no actualizarse la imagen fallarán.

2021-12-17 09:36 UTC, Antobio17 commented on docs/docker.md
> +- Acceso a mayor cantidad de paquetes,
No se si es la mejor opción para elegir un contenedor, cuantos mas paquetes más posibilidades de encontrarte deprecations o posibles fallos a futuro.

2021-12-17 09:36 UTC, Antobio17 commented on docs/docker.md
> +
Creo que faltaría haber probado los distintos contenedores base seleccionados de inicio y comparar por ejemplo las facilidades o inconvenientes para el montaje de la imagén, ver si hay una diferencia significativa de tiempo referente a la ejecución de los tests, etc.

2021-12-17 10:08 UTC, alexespana requested changes
Buenas @morevi ,  creo que los errores principales están en la documentación. Échale un ojo a lo que te he comentado más abajo.

2021-12-17 10:08 UTC, alexespana commented on .github/workflows/dockerhub.yml
> +      - .github/workflows/dockerhub.yml
Creo que no tiene sentido que añadas a paths el mismo fichero del workflow, realmente cuando tendrías que actualizar la imagen a Dockerhub sería cuando cambiaran las dependencias o también el readme en este caso. Por cierto, el archivo .lock sería necesario añadirlo también.

2021-12-17 10:08 UTC, alexespana commented on docs/docker.md
> +- Acceso a mayor cantidad de paquetes,
Pienso igual que mi compañero, no creo que tener la mayor cantidad de paquetes sea un requisito razonable, ya que puedes tener gran cantidad de paquetes que realmente son innecesarios.

2021-12-17 10:08 UTC, alexespana commented on docs/docker.md
> +- Última version de python y de SO lts disponible.
No por ser la ultima versión de python significa que sea la más adecuada para tu contenedor.

2021-12-17 10:08 UTC, alexespana commented on docs/docker.md
> +`python3.10-bullseye` cumple los requisitos de versiones y de acceso a paquetes. Pero `python3.10-slim-bullseye`, también cumple el requisito de reducir el tamaño.
Para mejorar la documentación, podrías incluir una tabla comparativa con los tiempos de creación y los tamaños de la imágen con distintas imágenes base, de forma que tengas algo claramenete objetivo con lo que realizar la elección.

2021-12-17 10:11 UTC, alexespana commented on .github/workflows/dockerhub.yml
> +      - .github/workflows/dockerhub.yml
Además, si se modificase el README pero no el resto, tendrías el readme desactualizado en DockerHub, aunque es un fallo menor.

2021-12-17 19:52 UTC, morevi commented on docs/docker.md
> +- Última version de python y de SO lts disponible.
Pero es la 3.10.1 la que tengo instalada localmente, ¿eso la hace más adecuada?

2021-12-17 22:28 UTC, morevi commented on docs/docker.md
> +- Última version de python y de SO lts disponible.
Vale, estoy viendo que usar 3.10 no es tan buena idea, acaba de salir hace escasos días

2021-12-17 22:34 UTC, morevi commented on .github/workflows/dockerhub.yml
> +      - .github/workflows/dockerhub.yml
Se me había quedado de ir haciendo pruebas. Lo del Readme, no me parecía correcto reconstruir la imagen cada vez que se modificase el Readme, por eso lo dejé fuera. También podría hacerse en un workflow aparte. Por ahora lo voy a dejar así, si JJ pide el cambio, no hay problema

2021-12-17 22:53 UTC, morevi commented
@alexespana @Antobio17 gracias por la revisión, he hecho algunos cambios teniendo en cuenta lo que dijisteis.
Lo mismo ya os había llegado notificación, de usar el boton de "re request review", si es así, disculpad 😅

2021-12-18 00:06 UTC, Antobio17 commented
> @alexespana @Antobio17 gracias por la revisión, he hecho algunos cambios teniendo en cuenta lo que dijisteis.
> 
> Lo mismo ya os había llegado notificación, de usar el boton de "re request review", si es así, disculpad 😅 

De nada! Si quieres que le volvamos a echar un vistazo o cualquier cosa o duda que te podamos ayudar nada mas que decirlo 👍 
Siempre teniendo en cuenta que no somos JJ 😆 esto es mas bien un debate de opiniones y si crees que los cambios sugeridos son buena idea nada mas que adoptarlos o incluso mejorarlos.

2021-12-18 02:12 UTC, alexespana commented
> @alexespana @Antobio17 gracias por la revisión, he hecho algunos cambios teniendo en cuenta lo que dijisteis. Lo mismo ya os había llegado notificación, de usar el boton de "re request review", si es así, disculpad sweat_smile

No hay de qué! Digo lo mismo que mi compañero, cualquier cosa que necesites solo tienes que decirlo :smile:

2021-12-18 08:09 UTC, morevi commented
@JJ Listo para revisión

2021-12-20 18:50 UTC, gomares commented
Vaya ,parece que llego tarde a la revisión. Estuve de viaje todo el fin de semana por un evento y no ví la mención que me hiciste @morevi . No obstante voy a echarle un ojo aunque creo que los problemas principales ya los han tratado mis compañeros.

2021-12-21 12:24 UTC, JJ requested changes
Todo bien, pero el milestone no incluye esto en su producto mínimamente viable (que tampoco está demasiado bien definido)

2021-12-21 12:36 UTC, morevi commented
@JJ he modificado el milestone, ¿puedo mergear ya? o Listo para revisión.

2021-12-21 12:43 UTC, JJ commented
> @JJ he modificado el milestone, ¿puedo mergear ya? o Listo para revisión.

No se trata de que edites el milestone, porque ahora resulta que hay un montón de issues (y el PR anterior #54) que not tienen absolutamente nada que ver con este milestone. Se trata de que *realmente* uséis los milestones para lo que son, y no simplemente para asignarles aleatoriamente un PR a cada uno. Aparte, tal como está ahora no queda claro qué es lo que hay que hacer antes ni qué funcionalidades tiene. Por favor, revisa bien el concepto de milestone y deja el que estaba como estaba y/o añádele lo necesario para que *realmente* incluya lo que se supone que has hecho dentro de él.

2021-12-21 13:22 UTC, morevi commented
@JJ Creo que ahora si 😓 . El milestone describe productos, y los requisitos para cumplirlo. He sacado los issues de CI a un nuevo milestone, de forma que los issues y PRs que hay describe lo que se ha hecho para cumplir los requisitos.
Listo para revisión

2021-12-21 19:49 UTC, JJ approved these changes
:+1:

2021-12-21 19:58 UTC, merged